message:
  not_allow: '现在不可以游玩'
  timeout: '验证超时'
  not_bind1: '请你绑定QQ'
  not_bind2: '使用/link2qq查看详情'
  not_adult1: '验证完毕，你不是成年人'
  not_adult2: '你将要受到防沉迷限制'
  is_adult1: '验证完毕，你是成年人'
  is_adult2: '你将不会受到防沉迷限制'
  checking1: '验证中'
  checking2: '请稍安勿躁'
  not_realname: '你没有实名认证'
settings:
  #设置为0不使用节假日API，设置为1使用本地节假日API（Holiday.json），设置为2使用网页节假日API http://timor.tech/api/holiday/year 设置成其他则不允许未成年人游玩
  use_holiday: 2
  time: 30
  #启用AuthMe支持可以让玩家在没有登录的时候不被倒计时
  authme: true